/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.SeleccionarNumeros;

import Estructuras.DoublyLinkedList;

/**
 *
 * @author Dylan
 */

public class EscogerBingo extends javax.swing.JDialog {

    /** Creates new form Bingo */
    DoublyLinkedList<Integer> numerosGanadores;

    public EscogerBingo(java.awt.Frame parent, boolean modal, DoublyLinkedList<Integer> numerosGanadores) {
        super(parent, modal);
        initComponents();
        for(int i=0;i<10;i++){
            comboNumBingo.addItem(Integer.toString(i));
            comboNumBingo1.addItem(Integer.toString(i));
            comboNumBingo2.addItem(Integer.toString(i));
            comboNumBingo3.addItem(Integer.toString(i));
            comboNumBingo4.addItem(Integer.toString(i));
            comboNumBingo5.addItem(Integer.toString(i));
            comboNumBingo6.addItem(Integer.toString(i));
            comboNumBingo7.addItem(Integer.toString(i));
            comboNumBingo8.addItem(Integer.toString(i));
        }
        this.numerosGanadores=numerosGanadores;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboNumLotto7 = new javax.swing.JComboBox<>();
        comboNumLotto8 = new javax.swing.JComboBox<>();
        comboNumBingo2 = new javax.swing.JComboBox<>();
        botonAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboNumBingo = new javax.swing.JComboBox<>();
        comboNumBingo1 = new javax.swing.JComboBox<>();
        comboNumBingo3 = new javax.swing.JComboBox<>();
        comboNumBingo4 = new javax.swing.JComboBox<>();
        comboNumBingo5 = new javax.swing.JComboBox<>();
        comboNumBingo6 = new javax.swing.JComboBox<>();
        comboNumBingo7 = new javax.swing.JComboBox<>();
        comboNumBingo8 = new javax.swing.JComboBox<>();
        comboNumBingo9 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecciones los 9 numeros que desea jugar.");

        comboNumBingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNumBingoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboNumBingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboNumBingo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboNumBingo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botonAceptar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboNumBingo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboNumBingo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboNumBingo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboNumBingo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboNumBingo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboNumBingo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboNumBingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumBingo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumBingo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumBingo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumBingo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumBingo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumBingo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumBingo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumBingo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAceptar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboNumBingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNumBingoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNumBingoActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        numerosGanadores.insert(Integer.parseInt((String) comboNumBingo.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumBingo1.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumBingo2.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumBingo3.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumBingo4.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumBingo5.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumBingo6.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumBingo7.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumBingo8.getSelectedItem()));
        dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EscogerBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EscogerBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EscogerBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EscogerBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                EscogerBingo dialog = new EscogerBingo(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JComboBox<String> comboNumBingo;
    private javax.swing.JComboBox<String> comboNumBingo1;
    private javax.swing.JComboBox<String> comboNumBingo2;
    private javax.swing.JComboBox<String> comboNumBingo3;
    private javax.swing.JComboBox<String> comboNumBingo4;
    private javax.swing.JComboBox<String> comboNumBingo5;
    private javax.swing.JComboBox<String> comboNumBingo6;
    private javax.swing.JComboBox<String> comboNumBingo7;
    private javax.swing.JComboBox<String> comboNumBingo8;
    private javax.swing.JComboBox<String> comboNumBingo9;
    private javax.swing.JComboBox<String> comboNumLotto7;
    private javax.swing.JComboBox<String> comboNumLotto8;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
