/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.SeleccionarNumeros;

import Estructuras.DoublyLinkedList;

/**
 *
 * @author Dylan
 */
public class EscogerLotto extends javax.swing.JDialog {

    /**
     * Creates new form Lotto
     */
    DoublyLinkedList<Integer> numerosGanadores;
    public EscogerLotto(java.awt.Frame parent, boolean modal, DoublyLinkedList<Integer> numerosGanadores) {
        super(parent, modal);
        initComponents();
        for(int i=0;i<10;i++){
            comboNumLotto.addItem(Integer.toString(i));
            comboNumLotto1.addItem(Integer.toString(i));
            comboNumLotto2.addItem(Integer.toString(i));
            comboNumLotto3.addItem(Integer.toString(i));
            comboNumLotto4.addItem(Integer.toString(i));
            comboNumLotto5.addItem(Integer.toString(i));
            comboNumLotto6.addItem(Integer.toString(i));
        }
        this.numerosGanadores=numerosGanadores;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboNumLoteria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboNumLotto = new javax.swing.JComboBox<>();
        comboNumLotto1 = new javax.swing.JComboBox<>();
        comboNumLotto2 = new javax.swing.JComboBox<>();
        comboNumLotto3 = new javax.swing.JComboBox<>();
        comboNumLotto4 = new javax.swing.JComboBox<>();
        comboNumLotto5 = new javax.swing.JComboBox<>();
        comboNumLotto6 = new javax.swing.JComboBox<>();
        botonAceptar = new javax.swing.JButton();

        comboNumLoteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNumLoteriaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Selecciones los 7 numeros que desea jugar.");

        comboNumLotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNumLottoActionPerformed(evt);
            }
        });

        comboNumLotto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNumLotto1ActionPerformed(evt);
            }
        });

        comboNumLotto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNumLotto2ActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboNumLotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboNumLotto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botonAceptar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboNumLotto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboNumLotto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboNumLotto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboNumLotto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboNumLotto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboNumLotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumLotto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumLotto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumLotto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumLotto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumLotto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumLotto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboNumLoteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNumLoteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNumLoteriaActionPerformed

    private void comboNumLottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNumLottoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNumLottoActionPerformed

    private void comboNumLotto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNumLotto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNumLotto1ActionPerformed

    private void comboNumLotto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNumLotto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNumLotto2ActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        numerosGanadores.insert(Integer.parseInt((String) comboNumLotto.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumLotto1.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumLotto2.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumLotto3.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumLotto4.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumLotto5.getSelectedItem()));
        numerosGanadores.insert(Integer.parseInt((String) comboNumLotto6.getSelectedItem()));
        dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EscogerLotto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EscogerLotto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EscogerLotto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EscogerLotto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                EscogerLotto dialog = new EscogerLotto(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JComboBox<String> comboNumLoteria;
    private javax.swing.JComboBox<String> comboNumLotto;
    private javax.swing.JComboBox<String> comboNumLotto1;
    private javax.swing.JComboBox<String> comboNumLotto2;
    private javax.swing.JComboBox<String> comboNumLotto3;
    private javax.swing.JComboBox<String> comboNumLotto4;
    private javax.swing.JComboBox<String> comboNumLotto5;
    private javax.swing.JComboBox<String> comboNumLotto6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
